volumes:
  grafana_data:
  prometheus_data:
  loki_data:

networks:
  CEM-KEA:
    driver: bridge
  
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - CEM-KEA
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Viewer
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_USER=true
      - GF_AUTH_ANONYMOUS_USER_ORG_ROLE=Viewer
      - GF_SERVER_ROOT_URL=https://monitor.cemdev.dk/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true

    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    environment:
      - MAIN_TARGET_IP=${MAIN_TARGET_IP}
    networks:
      - CEM-KEA
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - CEM-KEA
    volumes:
      - loki_data:/loki
      - ./config/loki-config.yml:/etc/loki/local-config.yaml
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    ports:
      - "9115:9115"
    networks:
      - CEM-KEA
    volumes:
      - ./config/blackbox.yml:/etc/blackbox_exporter/config.yml
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9115/-/healthy || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # alertmanager:
  #   image: prom/alertmanager:latest
  #   container_name: alertmanager
  #   ports:
  #     - "9093:9093"
  #   networks:
  #     - CEM-KEA
  #   volumes:
  #     - ./config/alerts.yml:/etc/alertmanager/alerts.yml
  #   command:
  #     - "--config.file=/etc/alertmanager/alerts.yml"
  #   restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_monitor
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/monitor.cemdev.dk:/etc/letsencrypt/live/monitor.cemdev.dk:ro
      - /etc/letsencrypt/archive/monitor.cemdev.dk:/etc/letsencrypt/archive/monitor.cemdev.dk:ro
    depends_on:
      grafana:
        condition: service_healthy
      prometheus:
        condition: service_healthy
      loki:
        condition: service_healthy
      blackbox_exporter:
        condition: service_healthy
    networks:
      - CEM-KEA
    restart: unless-stopped