volumes:
  grafana_data:
  prometheus_data:
  loki_data:
  traefik_data:

networks:
  CEM-KEA:
    driver: bridge

services:
  traefik:
    image: traefik:v3.2.0
    container_name: traefik
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/acme.json
      - --metrics.prometheus=true
      - --log.level=DEBUG
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/acme.json:/acme.json
    networks:
      - CEM-KEA
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`monitor.cemdev.dk`) && PathPrefix(`/grafana`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      #- "traefik.http.middlewares.grafana-stripprefix.stripprefix.prefixes=/grafana"
      #- "traefik.http.routers.grafana.middlewares=grafana-stripprefix"
    networks:
      - CEM-KEA
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Viewer
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_SERVER_ROOT_URL=https://monitor.cemdev.dk/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`monitor.cemdev.dk`) && PathPrefix(`/prometheus`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls.certresolver=myresolver"
      - "traefik.http.middlewares.prometheus-stripprefix.stripprefix.prefixes=/prometheus"
      - "traefik.http.routers.prometheus.middlewares=prometheus-stripprefix"
    networks:
      - CEM-KEA
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  loki:
    image: grafana/loki:latest
    container_name: loki
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`monitor.cemdev.dk`) && PathPrefix(`/loki`)"
      - "traefik.http.routers.loki.entrypoints=websecure"
      - "traefik.http.routers.loki.tls.certresolver=myresolver"
      - "traefik.http.middlewares.loki-stripprefix.stripprefix.prefixes=/loki"
      - "traefik.http.routers.loki.middlewares=loki-stripprefix"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
    networks:
      - CEM-KEA
    volumes:
      - loki_data:/loki
      - ./config/loki-config.yml:/etc/loki/local-config.yaml
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blackbox.rule=Host(`monitor.cemdev.dk`) && PathPrefix(`/blackbox`)"
      - "traefik.http.routers.blackbox.entrypoints=websecure"
      - "traefik.http.routers.blackbox.tls.certresolver=myresolver"
      - "traefik.http.middlewares.blackbox-stripprefix.stripprefix.prefixes=/blackbox"
      - "traefik.http.routers.blackbox.middlewares=blackbox-stripprefix"
    networks:
      - CEM-KEA
    volumes:
      - ./config/blackbox.yml:/etc/blackbox_exporter/config.yml
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9115/-/healthy || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
