global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['52.169.32.176:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['52.169.32.176:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['52.169.32.176:8082']

  - job_name: 'postgres'
    static_configs:
      - targets: ['52.169.32.176:9187']
  
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://52.169.32.176:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  - job_name: 'whoknows-backend'
    metrics_path: '/api/probe'
    static_configs:
      - targets: ['52.169.32.176:8080']