name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GF_SECURITY_ADMIN_USER: ${{ secrets.GF_SECURITY_ADMIN_USER }}
      GF_SECURITY_ADMIN_PASSWORD: ${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}
      MAIN_TARGET_IP: ${{ secrets.MAIN_TARGET_IP }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to AWS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_VM_USER }}@${{ secrets.AWS_VM_IP }} << EOF
          set -e

          echo "Navigating to project directory..."
          cd ~/whoknows_monitor

          echo "Stopping running containers..."
          docker compose down || echo "No containers running"

          echo "Writing environment variables to .env file..."
          cat <<EOT > .env
          GF_SECURITY_ADMIN_USER=${{ secrets.GF_SECURITY_ADMIN_USER }}
          GF_SECURITY_ADMIN_PASSWORD=${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}
          MAIN_TARGET_IP=${{ secrets.MAIN_TARGET_IP }}
          EOT

          echo "Pulling latest code..."
          git pull || exit 1

          echo "Updating Docker images..."
          docker compose pull || exit 1

          echo "Starting containers..."
          docker compose up -d || exit 1

          echo "Cleaning up Docker..."
          docker system prune -f

          echo "Deployment successful!"
          EOF
